package edu.realemj.assign07;
//NOTE: CHANGE realemj to YOUR SITNETID!!!

import edu.realemj.testing.GeneralTesting;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.io.IOException;

public class Test_Thunderdome {

    @Test()
    public void testMain() throws IOException {

        String [] allInputs = {
                "d\n"+
                "s\n"+
                "s\n"+
                "a\n"+
                "w\n"+
                "a\n"+
                "a\n"+
                "x\n"
        };

        GeneralTesting.OutPack [] correctOutputs = {
                new GeneralTesting.OutPack(
                        """
                        MAP:
                        O..............................
                        ...............B.............O.
                        ...............................
                        .O...........B.P.B.............
                        ..............B................
                        .....................O.........
                        ...............................
                        
                        Enter action:
                        MAP:
                        .O.............B...............
                        ............................O..
                        ...............................
                        ..O.........B...P.B............
                        .............B.................
                        ....................O..........
                        ...............................
                        
                        Enter action:
                        MAP:
                        ..O............................
                        ...........................O...
                        ...............................
                        ...O.......B.......B...........
                        ............B...P..............
                        ...................O...........
                        ...............................
                        
                        Enter action:
                        MAP:
                        ...O...........................
                        ..........................O....
                        ...............................
                        ....O.....B.........B..........
                        ...........B...................
                        ................P.O............
                        ...............................
                        
                        Enter action:
                        MAP:
                        ....O..........................
                        .........................O.....
                        ...............................
                        .....O...B...........B.........
                        ..........B....................
                        ...............P.O.............
                        ...............................
                        
                        Enter action:
                        MAP:
                        .....O.........................
                        ........................O......
                        ...............................
                        ......O.B.............B........
                        .........B.....P...............
                        ................O..............
                        ...............................
                        
                        Enter action:
                        MAP:
                        ......O........................
                        .......................O.......
                        ...............................
                        .......B...............B.......
                        ........B.....P................
                        ...............O...............
                        ...............................
                        
                        Enter action:
                        MAP:
                        .......O.......................
                        ......................O........
                        ...............................
                        ......B.O...............B......
                        .......B.....P.................
                        ..............O................
                        ...............................   
                                             
                        Enter action:
                        """, 
                        ""),
        };

        for(int i = 0; i < allInputs.length; i++) {

            // Start redirect
            GeneralTesting.StreamPack.getInstance().start(allInputs[i]);

            // Call main
            Thunderdome.main(null);

            // Stop redirect
            GeneralTesting.OutPack programOutput = GeneralTesting.StreamPack.getInstance().stop();

            // Compare to correct result
            Assert.assertEquals(programOutput, correctOutputs[i]);

            System.out.println(correctOutputs[i]);
        }
    }
}
